### PR TITLE
Argument inversion

### PR DESCRIPTION
**Pull request by vbfox**
Also
* Bump dependencies (And update to netstandard2.0 as it's now required)
* Update FAKE to get a dotnet install that isn't buggy (The previous one always downloaded itself on some configurations)
* Fix the SDK version in `global.json` so that dotnet CLI and FAKE are agreeing with each-other

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@et1975 Do you want me to manage this repo ?

Or do you want to do manage all the repos in the process of migration to the new Elmish version ?

**Comment by et1975** [comment]
@MangelMaxime Please do, as I won't be able to publish it anyways.

**Comment by MangelMaxime** [comment]
@et1975 Ok I will do.

I also send you a nuget invitation just to not be the only manager of the repo. We never know :)

**Comment by MangelMaxime** [comment]
Thanks you @vbfox 
I released it under: `2.0.0-beta-1`

**Pull request merged**
