### PR TITLE
WIP Fable/Elmish v4 upgrade

### LINKED ISSUE #40: Needs update for Fable 4
### Description
Need update for Fable 4 as it fails below error

```
/src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/common.fs(64,9): (64,15) error FSHARP: The value or constructor 'ofType' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/common.fs(90,9): (90,15) error FSHARP: The value or constructor 'ofType' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/common.fs(116,9): (116,15) error FSHARP: The value or constructor 'ofType' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(184,12): (184,74) error FSHARP: Type mismatch. Expecting a
    'Program<'arg,'model,'msg,'view> -> Program<'arg,obj,obj,obj>'    
but given a
    '(('msg -> bool) * ('model -> unit) -> (Msg<'msg> -> bool) * (Model<'model> -> unit)) -> Program<'a,'model,'msg,'b> -> Program<'a,Model<'model>,Msg<'msg>,'b>'    
The type 'Program<'arg,'model,'msg,'view>' does not match the type '('msg -> bool) * ('model -> unit) -> (Msg<'msg> -> bool) * (Model<'model> -> unit)' (code 1)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(184,62): (184,74) error FSHARP: Type mismatch. Expecting a
    '('model -> Sub<'msg>) -> Model<'model> -> Sub<Msg<'msg>>'    
but given a
    '('model -> Cmd<'a>) -> Model<'model> -> Cmd<Msg<'a>>'    
The type 'SubId * Subscribe<'msg>' does not match the type 'Effect<'a>' (code 1)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(213,44): (213,52) error FSHARP: The value, constructor, namespace or type 'Internal' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(218,44): (218,52) error FSHARP: The value, constructor, namespace or type 'Internal' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(223,44): (223,52) error FSHARP: The value, constructor, namespace or type 'Internal' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(226,36): (226,44) error FSHARP: The value, constructor, namespace or type 'Internal' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(229,36): (229,44) error FSHARP: The value, constructor, namespace or type 'Internal' is not defined. (code 39)
./src/Client/fable-output/fable_modules/Fable.Elmish.HMR.5.2.0/hmr.fs(231,28): (231,36) error FSHARP: The value, constructor, namespace or type 'Internal' is not defined. (code 39)
Please provide a succinct description of your issue.
```

### PR DESCRIPTION
**Pull request by kspeakman**
resolves #40

Status
|||
|--|--|
| Compiles | ✔️ |
| Tests work | ✔️ |
| Docs build | ❌ |

TODO
- [x] broken dep: Tests proj, nuget Feliz.Bulma -> Fable.React, needs to be Fable.ReactDom etc
    Options
    - A: wait for Felize.Bulma beta with latest Fable React libs
    - **B: remove dependency for now, change views to use Bulma CSS**
    - C: other suggestions?
 - [ ] broken dep: docs, npm Nacara -> React v17, other libs require v18

### CODE REVIEW

**Comment by kspeakman** [comment]
@MangelMaxime Is it possible to isolate the Nacara deps from the Test project deps? Was thinking it might be possible to have it in a separate folder with its own package.json. I'm not practiced in advanced front-end build scenarios.

**Comment by MangelMaxime** [comment]
Sorry, I didn't see that you took into account some of my comments and so was still waiting for after you... (my bad)

I will have a look at the dependencies stuff.

In theory, React 18 is compatible with React 17 with some warning.

**Comment by kspeakman** [comment]
No worries!

Ah, yes. I seem to be using React 18 with the older Fable.React package and see a warning on every render. I think this works because Fable.React is dotnet and can't enforce npm package deps. Could Nacara's npm deps be changed to allow both v17 and v18?

**Comment by MangelMaxime** [comment]
Supporting both react 17 and 18 is not that easy, because some import needs to be different.

I am just going to support React 18 for now. Nacara is under a complete rewrite right now, to delegate most a lost of responsibility to an external tool so I can focus on what make add values to Nacara (providing a good template for documentation + F# API generation in the future)

**Pull request merged**
