### PR TITLE
Update to Fable.Core 3

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This PR:

- Makes Elmish.HMR compatible with Fable.Core 3
- Because the idea is to deprecate the Fable.Import packages, for now I've just copied the HMR bindings directly to remove the Fable.Import.HMR dependency
- I've removed the `#else .. #endif` alternatives. In production the app should just default to Elmish.Program methods
- Is it correct to just use `id` for `syncDispatch` field?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
What will be the replacement of `Fable.Import.HMR` because it can be used in other project? 

The `#else .. #endif` where defaulting to the `Elmish.Program` methods because they were marked as inlined. Note sure if this is better or not to have them.

> Is it correct to just use id for syncDispatch field?

`id` is fine for Fable usage.

@et1975 Wasn't Fable.Elmish `3.0.0-beta-*` stopped for now because you weren't happy with the reimplementation of the mailbox and with using a record to represent the `program`?

**Comment by alfonsogarciacaro** [comment]
Not sure if another project is using Fable.Import.HMR, but if that's the case, we'll need a maintainer that takes ownership of the packages and moves it to a different repo :)

**Comment by et1975** [comment]
@MangelMaxime I'll update on the status of the beta in elmish repo.

**Comment by alfonsogarciacaro** [comment]
Would it be possible to have a beta release of this? Thanks! 😸

**Comment by MangelMaxime** [comment]
Yes, I will release it.

And we will update this repo when Elmish 3 API has been made stable.

**Comment by MangelMaxime** [comment]
I manually merge your branch into the branch `vNext` and I release it under `4.0.0-beta-3`

**Pull request merged**
